version: '3'
services:
  bluesky_rss_bot:
    build: .
    container_name: bluesky_rss_bot
    env_file: .env  # Ladda miljövariabler från .env-filen
    volumes:
      - /volume1/docker/bluebot:/app  # Mappar mappen på NAS till containern
    restart: always
